version: "2"
services:
  master:
    container_name: master
    image: nobudev/master:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8888"
      - "10005:22"
    volumes:
      - "~/dev/projects/master:/home/jovyan/dev/projects/master"
